[versions]
agp = "8.10.1"
kotlin = "2.0.21"
coreKtx = "1.17.0"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
lifecycleRuntimeKtx = "2.9.4"
activityCompose = "1.11.0"
composeBom = "2025.10.01"
appcompat = "1.7.1"
material = "1.13.0"

#Hilt Plugin Version
hiltPluginVersion ="2.57.1"
composeNavigation="2.9.5"
hiltNavigationVersion="1.3.0"

#KSP
kspPluginVersion ="2.0.21-1.0.27"

#Coroutines
kotlinxCoroutinesCore ="1.10.2"

#Datastore
dataStoreVersion="1.1.7"

#Retrfoit
retrofitVersion="2.9.0"

#Moshi
moshiVersion="1.15.0"

#OkHTTP3
okhttpVersion="4.12.0"

#Coil -> Image Loading
coilVersion ="2.5.0"

#Material3
material3Version="1.4.0"

#Material - Icons
materialIconsVersion="1.7.5"
pagingCommonAndroid = "3.3.6"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }

#Hilt
hilt-android= {group="com.google.dagger", name="hilt-android", version.ref="hiltPluginVersion"}
hilt-compiler={group="com.google.dagger", name="hilt-compiler", version.ref="hiltPluginVersion"}
androidx-hilt-navigation={group="androidx.hilt", name="hilt-navigation-compose", version.ref="hiltNavigationVersion"}

#Navigation
androidx-navigation={group="androidx.navigation", name="navigation-compose", version.ref="composeNavigation"}

#Coroutines
kotlinx-coroutines-core ={group="org.jetbrains.kotlinx", name="kotlinx-coroutines-core", version.ref="kotlinxCoroutinesCore"}

#DataStore
androidx-datastore = {group="androidx.datastore", name="datastore-preferences", version.ref="dataStoreVersion"}

#Retrofit
retrofit = {group="com.squareup.retrofit2", name="retrofit", version.ref="retrofitVersion"}
retrofit-converter-moshi = {group="com.squareup.retrofit2", name="converter-moshi", version.ref="retrofitVersion"}

#Moshi
moshi-kotlin = {group="com.squareup.moshi", name="moshi-kotlin", version.ref="moshiVersion"}

#Okhttp3
okhttp3 ={group="com.squareup.okhttp3", name="okhttp", version.ref="okhttpVersion"}
okhttp3-logging-interceptor = {group="com.squareup.okhttp3", name="logging-interceptor", version.ref="okhttpVersion"}
okhttp3-url-connection= {group="com.squareup.okhttp3", name="okhttp-urlconnection", version.ref="okhttpVersion"}

#Coil
coil-compose = {group="io.coil-kt", name="coil-compose", version.ref="coilVersion"}

#ViewModel-Compose
androidx-lifecycle-viewmodel-compose={group="androidx.lifecycle", name="lifecycle-viewmodel-compose", version.ref="lifecycleRuntimeKtx"}

#Material3
androidx-compose-material3={group="androidx.compose.material3", name="material3", version.ref="material3Version"}

#Material - Icons
androidx-compose-material-icons = {group ="androidx.compose.material", name="material-icons-extended", version.ref="materialIconsVersion"}

#Paging3
androidx-paging-common-android = { group = "androidx.paging", name = "paging-common-android", version.ref = "pagingCommonAndroid" }
androidx-paging-compose = { group = "androidx.paging", name = "paging-compose", version.ref = "pagingCommonAndroid" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }

#Kotlin
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

#Compose
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }

#Hilt
hilt-android = {id="com.google.dagger.hilt.android", version.ref="hiltPluginVersion"}

#KSP
kotlin-ksp={id="com.google.devtools.ksp", version.ref="kspPluginVersion"}

#Library
android-library = { id = "com.android.library", version.ref = "agp" }



